Add all contributors to the README
lambdaclass/yet-another-swap pull request #104
Opened 2023-09-21 20:21 UTC by WiseMrMusa

Closes #103

2023-09-21 21:13 UTC, rcatalan98 approved these changes
Thanks for contributing!

2023-09-21 21:16 UTC, rcatalan98 requested changes
We should find a way to limit the avatars to the same size

2023-09-22 00:42 UTC, rcatalan98 approved these changes
Great work again! Thanks!

2023-09-22 02:18 UTC, dpinones approved these changes

2023-09-22 03:41 UTC, merged