Error handling
lambdaclass/yet-another-swap pull request #133
Opened 2023-10-08 17:14 UTC by faytey

A draft of the error-handling techniques used for testing purposes, kindly let me know if the method used so far is acceptable. Thanks

2023-10-19 19:34 UTC, uri-99 requested changes
some format errors. You should run `make fmt` before pushing

2023-10-19 19:34 UTC, uri-99 commented on src/contracts/yas_pool.cairo
> +use super::IYASPool;
format error. You should run `make fmt` before pushing

2023-10-19 19:34 UTC, uri-99 commented on src/libraries/tick.cairo
> +use super::{ITick, Info};
format error. You should run `make fmt` before pushing

2023-10-19 19:34 UTC, uri-99 commented on src/libraries/tick_bitmap.cairo
> +use super::ITickBitmap;
format error. You should run `make fmt` before pushing

2023-10-19 19:34 UTC, uri-99 commented on src/tests/test_libraries/test_bit_math.cairo
> +use integer::BoundedInt;
format error. You should run `make fmt` before pushing

2023-10-19 19:34 UTC, uri-99 commented on src/tests/test_libraries/test_bit_math.cairo
> +use integer::BoundedInt;
format error. You should run `make fmt` before pushing

2023-10-19 19:53 UTC, uri-99 requested changes
some missing `#[available_gas()]` attributes in `#[tests]`. It is important to evaluate gas consumption, to ensure there are no deadlocks.

2023-10-19 19:53 UTC, uri-99 commented on src/tests/test_libraries/test_bit_math.cairo
> +        fn msb_happy_path() -> Result<u8, felt252> {
`#[test]` should contain `#[available_gas()]` attribute 
```suggestion
        #[available_gas(200000000)]
        fn msb_happy_path() -> Result<u8, felt252> {
```

2023-10-19 19:53 UTC, uri-99 commented on src/tests/test_libraries/test_bit_math.cairo
> +        fn msb_larger_number() -> Result<u8, felt252> {
`#[test]` should contain `#[available_gas()]` attribute

2023-10-19 19:53 UTC, uri-99 commented on src/tests/test_libraries/test_bit_math.cairo
> +        fn msb_bigger_number() -> Result<u8, felt252> {
`#[test]` should contain `#[available_gas()]` attribute

2023-10-19 19:53 UTC, uri-99 commented on src/tests/test_libraries/test_bit_math.cairo
> +        fn msb_maximum_256() -> Result<u8, felt252> {
`#[test]` should contain `#[available_gas()]` attribute

2023-10-19 19:53 UTC, uri-99 commented on src/tests/test_libraries/test_bit_math.cairo
> +        fn msb_random_number() -> Result<u8, felt252> {
`#[test]` should contain `#[available_gas()]` attribute

2023-10-19 19:53 UTC, uri-99 commented on src/tests/test_libraries/test_bit_math.cairo
>          fn msb_number_zero() {
`#[test]` should contain `#[available_gas()]` attribute

2023-10-19 19:53 UTC, uri-99 commented on src/tests/test_libraries/test_bit_math.cairo
> +        fn lsb_happy_path() -> Result<u8, felt252> {
`#[test]` should contain `#[available_gas()]` attribute

2023-10-19 19:53 UTC, uri-99 commented on src/tests/test_libraries/test_bit_math.cairo
> +        fn lsb_larger_number() -> Result<u8, felt252> {
`#[test]` should contain `#[available_gas()]` attribute

2023-10-19 19:53 UTC, uri-99 commented on src/tests/test_libraries/test_bit_math.cairo
> +        fn lsb_bigger_number() -> Result<u8, felt252> {
`#[test]` should contain `#[available_gas()]` attribute

2023-10-19 19:53 UTC, uri-99 commented on src/tests/test_libraries/test_bit_math.cairo
> +        fn lsb_maximum_256() -> Result<u8, felt252> {
`#[test]` should contain `#[available_gas()]` attribute

2023-10-19 19:53 UTC, uri-99 commented on src/tests/test_libraries/test_bit_math.cairo
> +        fn lsb_random_number() -> Result<u8, felt252> {
`#[test]` should contain `#[available_gas()]` attribute

2023-10-19 19:53 UTC, uri-99 commented on src/tests/test_libraries/test_bit_math.cairo
>          fn lsb_number_zero() {
`#[test]` should contain `#[available_gas()]` attribute

2023-10-19 20:02 UTC, uri-99 requested changes
Tests should `assert()` different values regarding the functionality being tested; to ensure the functionality fails when it should fail and also to ensure that it doesn't fail when it shouldn't

2023-10-19 20:12 UTC, faytey commented
So maybe I got the task wrong, I was asked to handle errors and replace all asserts, also to use the Result method for error handling. Please can you help explain the task properly so I do the correct thing please thanks

2023-10-20 18:32 UTC, rcatalan98 commented
> So maybe I got the task wrong, I was asked to handle errors and replace all asserts, also to use the Result method for error handling. Please can you help explain the task properly so I do the correct thing please thanks

Hi @faytey! No problem maybe we weren't clear enough with the issue. The task is to refactor the listed function to return `Result` instead of having the assert in this library functions. So for `testing` this functions you will receive whatever the function returns and use patter matching to check if there was an error or not. This same strategy should be used by any function that calls the underlying library functions.

Is that clear?

2023-10-31 12:34 UTC, closed without merging