merge 'make tests FILTER=filter'
lambdaclass/yet-another-swap pull request #136
Opened 2023-10-10 00:47 UTC by uri-99

2023-10-11 18:55 UTC, rcatalan98 requested changes

2023-10-11 18:55 UTC, rcatalan98 commented on README.md
> +make test FILTER=Mint
Is not clear if this filters for the name of the test or mod of tests. Could you provide more information and a more detailed example?

2023-10-11 18:55 UTC, rcatalan98 commented on Makefile
> +RESET := \033[0m
Should this be defined somewhere else? This could be passed by the user if it's defined here

2023-10-14 17:53 UTC, rcatalan98 approved these changes

2023-10-17 13:57 UTC, dpinones approved these changes

2023-10-18 14:54 UTC, rcatalan98 requested changes
Please make the necessary changes. Do we need to add to the README that `grep` is a requirement to run specific tests in this project?

2023-10-18 14:54 UTC, rcatalan98 commented on Makefile
> +tests:
```suggestion
test:
```

2023-10-18 14:54 UTC, rcatalan98 commented on README.md
> +make test FN=test_invalid_max_tick
This test doesn't work. After running it I get the following error:
`scarb test | filter by test_invalid_max_tick
     Running cairo-test yas with filter=test_invalid_max_tick
testing yas ...

grep: invalid option -- P
usage: grep [-abcdDEFGHhIiJLlMmnOopqRSsUVvwXxZz] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1019:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

2023-10-18 14:54 UTC, rcatalan98 commented on README.md
> +make test MOD=Mint FN=test_invalid_max_tick
This test doesn't work. I get the following error:
`

`
Also there is no` test_invalid_max_tick` function in the Mint module.

2023-10-18 15:49 UTC, rcatalan98 commented
I just checked and it looks like you can replace all the grep with just `scarb test -f test_name` and it will only execute that specific function. No need for wrapper code anymore

2023-10-23 21:22 UTC, rcatalan98 approved these changes
Great work! Before merging please merge the latest changes from main.

2023-10-24 01:40 UTC, merged