Add burn in YASPool
lambdaclass/yet-another-swap pull request #139
Opened 2023-10-17 18:40 UTC by dpinones

Closes: #91

2023-11-07 15:43 UTC, rcatalan98 requested changes

2023-11-07 16:09 UTC, rcatalan98 commented on crates/yas_core/src/contracts/yas_pool.cairo
> +        ) -> (PositionInfo, i256, i256) // TODO: noDelegateCall
```suggestion
        ) -> (PositionInfo, i256, i256)
```

2023-11-16 11:13 UTC, dpinones commented on crates/yas_core/src/tests/test_contracts/test_yas_pool.cairo
> +        // TODO: Uncomment when the swap has tests
✔️

2023-11-16 11:14 UTC, dpinones commented on crates/yas_core/src/contracts/yas_pool.cairo
> +        /// @dev noDelegateCall is applied indirectly via _modifyPosition
✔️

2023-11-16 11:14 UTC, dpinones commented on crates/yas_core/src/contracts/yas_pool.cairo
> +        ) -> (PositionInfo, i256, i256) // TODO: noDelegateCall
✔️

2023-11-16 20:20 UTC, dubzn reviewed
Seems good to me! But I've been reviewing, and there are several test cases missing that are in UniswapV3Pool.spec.ts and the burn() function is used. I'm not sure if you plan to add them later, or it would be good to include them directly in this PR. What do you think?

in the `describe('#mint', () => { ..` theres some tests, can we see it later in a meet?

2023-11-17 15:35 UTC, dubzn approved these changes

2023-11-17 15:50 UTC, uri-99 approved these changes

2023-12-01 21:11 UTC, rcatalan98 commented
For the future we will need to remove the ToDo in the tests to be sure the behavior is the correct one.

2023-12-01 21:11 UTC, merged