Add Error Handling For Libraries
lambdaclass/yet-another-swap pull request #150
Opened 2023-10-26 20:03 UTC by Gianfranco99

2023-11-16 21:26 UTC, dubzn requested changes
GJ, very nice! I'll leave some brief comments related to the function names. I'd also like to discuss whether we want to name them `check_x` or `assert_x`.

References: [Uniswap Error Codes](https://docs.uniswap.org/contracts/v3/reference/error-codes)

2023-11-16 21:26 UTC, dubzn commented on crates/yas_core/src/libraries/bit_math.cairo
> +    fn check_value(x: u256) -> Result<(), felt252> {
```suggestion
    fn check_gt_zero(x: u256) -> Result<(), felt252> {
```

2023-11-16 21:26 UTC, dubzn commented on crates/yas_core/src/libraries/liquidity_math.cairo
> +    fn check_value(x: u128, y: u128) -> Result<(), felt252> {
```suggestion
    fn check_liquidity_sub(x: u128, y: u128) -> Result<(), felt252> {
```

2023-11-16 21:26 UTC, dubzn commented on crates/yas_core/src/libraries/liquidity_math.cairo
> +    fn check_overflowing_add(x: u128, y: u128) -> Result<(), felt252> {
```suggestion
    fn check_liquidity_add(x: u128, y: u128) -> Result<(), felt252> {
```

2023-11-16 21:26 UTC, dubzn commented on crates/yas_core/src/tests/test_libraries/test_sqrt_price_math.cairo
> +        #[should_panic(expected: ('sqrt_ratio_AX96 cannot be neg',))]
:fire:

2023-11-16 21:26 UTC, dubzn commented on crates/yas_core/src/libraries/tick_math.cairo
> +        }; // TODO: review this error in the future. This is the original error from UniswapV3.
```suggestion
        }; 
```

2023-11-16 21:26 UTC, dubzn commented on crates/yas_core/src/libraries/tick_math.cairo
> +    fn check_abs_tick(tick: i32) -> Result<(), felt252> {
```suggestion
    // T: The given tick must be less than, or equal to, the maximum tick
    fn check_tick(tick: i32) -> Result<(), felt252> {
```

2023-11-17 15:53 UTC, uri-99 commented on crates/yas_core/src/libraries/bit_math.cairo
> +    fn check_value(x: u256) -> Result<(), felt252> {
+1

2023-11-17 15:54 UTC, uri-99 commented on crates/yas_core/src/libraries/liquidity_math.cairo
> +    fn check_value(x: u128, y: u128) -> Result<(), felt252> {
+1

2023-11-17 15:54 UTC, uri-99 commented on crates/yas_core/src/libraries/liquidity_math.cairo
> +    fn check_overflowing_add(x: u128, y: u128) -> Result<(), felt252> {
+1

2023-11-17 16:10 UTC, uri-99 requested changes
Here, the process of the check should be done inside the check_product_overflow function, otherwise, check_product_overflow is just a check_equals

2023-11-17 16:10 UTC, uri-99 commented on crates/yas_core/src/libraries/sqrt_price_math.cairo
> +            match check_product_overflow(FP64x96Impl::new(product / amount, false), sqrtPX96) {
```suggestion
            match check_product_overflow(product, amount, false, sqrtPX96) {
```

2023-11-17 16:10 UTC, uri-99 commented on crates/yas_core/src/libraries/sqrt_price_math.cairo
> +            Result::Ok(())
```suggestion
    fn check_product_overflow(product: u256, amount: u256, sign: bool, value_2: FixedType) -> Result<(), felt252> {
        if FP64x96Impl::new(product / amount, sign) == value_2 {
            Result::Ok(())
```

2023-11-17 16:22 UTC, uri-99 commented on crates/yas_core/src/libraries/sqrt_price_math.cairo
> +        }
Every operation costs gas, so we should minimize unnecessary operations to save on gas.
```suggestion
        if sign {
            Result::Err('sqrt_ratio_AX96 cannot be neg')
        } else {
            Result::Ok(())
        }
```

2023-11-17 16:27 UTC, uri-99 requested changes
Good job! I left just some small suggestions to improve the style of coding, for efficiency and comprehension. 👍

2023-11-22 18:35 UTC, uri-99 approved these changes

2023-11-22 18:37 UTC, dubzn submitted a review, later dismissed

2023-12-11 13:44 UTC, dpinones approved these changes

2023-12-23 14:47 UTC, merged