Add -Inf case
lambdaclass/yet-another-swap pull request #196
Opened 2023-12-05 20:50 UTC by uri-99

This PR adds execution_price: -Infinity case
This PR also cleans and adds this to the .py parser

2023-12-05 22:45 UTC, dubzn approved these changes

2023-12-05 22:47 UTC, dubzn requested changes

2023-12-05 22:47 UTC, dubzn commented on scripts/utility/swap_expected_result.txt
remove this please!

2023-12-05 22:47 UTC, dubzn commented on scripts/utility/uni_values.txt
remove this please :pray:

2023-12-05 22:47 UTC, dubzn commented on scripts/utility/parse_to_cairo_struct.py
> +# },
why are we changing this in this PR? :thinking:

2023-12-06 15:39 UTC, rcatalan98 commented on scripts/utility/uni_values.txt
Should we add the `.txt` to the `gitignore` file? So we can avoid this happening in the future

2023-12-06 16:12 UTC, rcatalan98 approved these changes

2023-12-06 16:12 UTC, rcatalan98 commented on crates/yas_core/src/tests/test_contracts/test_yas_pool.cairo
> +            '-Infinity'.into()
Can you add a comment describing how this works? Something similar to what you mentioned in Slack.
Describing the different cases and the output for each one

2023-12-11 15:25 UTC, merged